# inventory.tf - Generate Ansible inventory file

resource "local_file" "ansible_inventory" {
  filename = "${path.module}/../ansible-playbooks/inventory/hosts.ini"
  
  content = <<-EOT
# Ansible Inventory - Auto-generated by Terraform
# Generated at: ${timestamp()}

[apache_servers]
%{~ for idx, ip in aws_instance.apache[*].public_ip ~}
apache-${idx + 1} ansible_host=${ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/webserver-key
%{~ endfor ~}

[nginx_servers]
%{~ for idx, ip in aws_instance.nginx[*].public_ip ~}
nginx-${idx + 1} ansible_host=${ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/webserver-key
%{~ endfor ~}

[webservers:children]
apache_servers
nginx_servers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOT
  
  file_permission = "0644"
  
  depends_on = [
    aws_instance.apache,
    aws_instance.nginx
  ]
}
